POST http://localhost:3000/api/chats
Content-Type: application/json

{
    "message": "Hello World"
}

###
GET http://localhost:3000/api/chats
Content-Type: application/json

###
@chatId = 700ff969-f621-4ec8-8bf4-5bcbf4ec5db5
GET http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
    "message": "Estou testando a API de novo"
}

###
@messageId = d74845e6-5c4f-49be-b37e-cd0d6aacaf7a
GET http://localhost:3000/api/messages/{{messageId}}/events
